### ISSUE TITLE
:screenimage does not work with decals

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#103]
:screenimage does not work with decals, only images.

**Comment by moo1210** [comment]
What do you mean by that, decals are images

**Comment by UsernameMissingOrNil** [comment]
Could be done by rendering the thumbnail image instead using: `https://www.roblox.com/asset-thumbnail/image?assetId=<DECALID>&width=420&height=420&format=png`
Bad because max resolution is 420x420, but would suffice.

Since Roblox don't provide an API accessible from within the engine, a HTTP request would have to be made to retrieve it: `http://f3xteam.com/bt/getDecalImageID/<DECALID>`
Bad because it's unknown how long this will be supported for, not all games have HTTP enabled, could go temporarily down and also extra latency.

Both methods would also require a call to [MarketplaceService:GetProductInfo](https://developer.roblox.com/en-us/api-reference/function/MarketplaceService/GetProductInfo) to detect whether the supplied ID was an image or decal, causing further delay and more points of failure.

**Comment by Deniied** [comment]
Fun fact: using ``https://www.roblox.com/asset-thumbnail/image?assetId=<DECALID>&width=420&height=420&format=png`` can be used to put pornographic material into a block game.

**Comment by pbstFusion** [comment]
Is this issue still occuring?

**Comment by joritochip** [comment]
There is unfortunately not much we can do about this without doing weird workarounds that involve using lower-quality thumbnails as the above reply suggested. Adonis should now at least inform you when you have used a decal ID rather than an image ID, with some explanation as to how to get the right ID, which is an improvement over the original behavior.
