### ISSUE TITLE
Adonis can't handle logs as large as 5000

### ISSUE THREAD

**Issue by doomdrvk** [Sceleratis/Adonis#114]
The scrollbar disappears after awhile and makes it unscrollable.

**Comment by NNickey** [comment]
You do know that Adonis caps logs, if you want to hold more or less, edit the settings.

**Comment by doomdrvk** [comment]
I'm talking about how the scrollbar can't even handle 2000 logs in the settings. Eventually for chat logs the scrollbar will disappear, leaving my admins unable to view any earlier chat logs.

**Comment by Cald-fan** [comment]
> I'm talking about how the scrollbar can't even handle 2000 logs in the settings. Eventually for chat logs the scrollbar will disappear, leaving my admins unable to view any earlier chat logs.

That would be a roblox problem because the scrolling frame is roblox related. As for the number of logs, Unless you changed the number the max number of logs is 1000.

**Comment by doomdrvk** [comment]
How is this only a Roblox Problem, there's a lot more the developer can do to fix this issue.

**Comment by NNickey** [comment]
It's a Roblox issue in that it's not able to handle a huge quantity of textlabels in a scrolling frame. Yes Adonis could destroy and create text labels based on where the Canvas position is at to show a lot more but it's better of an issue to just limit it until Roblox fixes it.

**Comment by Sceleratis** [comment]
> How is this only a Roblox Problem, there's a lot more the developer can do to fix this issue.

The limit was added due to issues with ROBLOX's ScrollingFrame. I don't expect most people will old logs as most of the time they're used to check something that happened recently. I could make my own implementation of a ScrollingaFrame, but I expect doing so would be more trouble than it's worth. Currently thinking of ways to bypass this limitation once list entries hit a certain threshold  (1000+?)

**Comment by doomdrvk** [comment]
Should have said this as soon as I thought of the idea, but why not add a new adonis setting to where we can enable page chat logs. That way you don't have to load all the entities on the scrollable and only have a set amount load at once.

**Comment by Sceleratis** [comment]
I feel like this is something I should have thought of and just integrated into the list ui....

**Comment by NNickey** [comment]
If converting into pages might be rough, creating and showing text labels that are only in the visible frame of the scrolling frame may be way easier to be able to handle over 5000 items. Simply only show the text labels that the scrolling frame is currently viewing on.
This lets you keep as much logs as you want and lets you handle as much as you want to in one frame.
Just check current CanvasPosition and AbsoluteSize.Y

**Comment by Sceleratis** [comment]
> If converting into pages might be rough, creating and showing text labels that are only in the visible frame of the scrolling frame may be way easier to be able to handle over 5000 items. Simply only show the text labels that the scrolling frame is currently viewing on.
> This lets you keep as much logs as you want and lets you handle as much as you want to in one frame.
> Just check current CanvasPosition and AbsoluteSize.Y

I was thinking of this as well as a potential solution, but I think I like the pages idea better since if we have too many logs in a single scrollingframe we *could* handle the "scrolling" part by looking at the canvas y and all that, but then we would have the issue of trying to scroll slightly all of the sudden lands you 100 logs down (more logs = more sensitive/difficult scrolling)

I could easily add something to the list gui where if the list table supplied is over maybe 100-250 entries, it will divide the entire table up into smaller list tables and displays page changing buttons which would, when clicked, repopulate the scrollframe using whatever the next page's content is. This wouldn't be too intensive for us to do as the number of entries would be small enough to just regenerate the list. This would also make stuff like refreshing a lot lighter on performance as it would again only need to regenerate a very small segment of the overall list. 

Right now I'm about to start on a college paper. If I have time I'll implement this later today or tomorrow.

**Comment by Sceleratis** [comment]
Update pushed. Let me know if something goes horribly wrong.
