### ISSUE TITLE
PrivateMessage is always using default theme regardless of settings.Theme

### ISSUE THREAD

**Issue by NNickey** [Sceleratis/Adonis#129]
When you adjust a custom theme to have Notification frame to a different color, the join game notification shows the new color, but when using :pm to load the PrivateMessage module, it's always loading the 'default' theme for the Notification frame but using the custom PrivateMessage module.

may attach a pull,idk

**Comment by joritochip** [comment]
This issue should be mostly fixed in this commit: https://github.com/Sceleratis/Adonis/commit/8290fccd767d5ed9530c2abeda1eff65a072c0a6

Basically, as long as the server has told the client to make a UI, the client should remember the last theme data that the server sent it and use that if the client did not set its own preferred theme in !client.
