### ISSUE TITLE
Included themes lack custom themes for menus such as !info

### ISSUE THREAD

**Issue by MrSaturnss** [Sceleratis/Adonis#136]
Another example would be the command bar.

**Comment by Sceleratis** [comment]
The themes currently in the script (with the exception of colorize since that themes guis on the fly) are based on the old "Hybrid" theme which has since been replaced by just "Default." Any missing guis are just pulled from the "Default" theme. Also, certain guis, like the UserPanel (which I think !info opens?) has some specific functionality in it, and is used to locally change settings/the theme, so I purposefully excluded it from built in themes to avoid issues (what if locally you change the theme, but the theme's userpanel is broken from updates, and now you can't change back?)

Ideally I'd like to make more themes that are just modules like the colorize one, where it will apply color schemes/effects/whatever on the fly so it doesn't need to rely on rebuilt guis.

**Comment by LolloDev5123** [comment]
Either close or do something hehe

**Comment by P3tray** [comment]
Either close or do something hehe
