### ISSUE TITLE
'Window' GUI always using Default theme

### ISSUE THREAD

**Issue by thomasthebro1** [Sceleratis/Adonis#146]
If you are using a different theme, the Window GUI always gets defaulted to the default theme, I've also noticed this with the private message command, the notification in the lower right corner of the screen is also using the default theme but if you use the `notify` command it uses the theme specified (e.g. Rounded)

**Comment by joritochip** [comment]
This issue should be mostly fixed in this commit: https://github.com/Sceleratis/Adonis/commit/8290fccd767d5ed9530c2abeda1eff65a072c0a6

Basically, as long as the server has told the client to make a UI, the client should remember the last theme data that the server sent it and use that if the client did not set its own preferred theme in !client.
