### ISSUE TITLE
Add option to disable oldlogs.

### ISSUE THREAD

**Issue by ccuser44** [Sceleratis/Adonis#214]
Add a setting to disable oldlogs.

**Comment by joritochip** [comment]
Whether or not this gets added, you can accomplish this with a plugin.
`return function() 
	server.Commands.OldLogs = nil 
	
	-- The code below this will COMPLETELY remove the OldCommandLogs functionality and it will stop saving old logs entirely. 
	-- Delete from here to the line if you just want the command disabled.
	server.Logs.ListUpdaters.OldCommandLogs = function()
		return {};
	end
	server.Logs.SaveCommandLogs = function() end
	--------------------------------------------------------------------
end`

**Comment by Sceleratis** [comment]
Can you elaborate on _why_ you want to disable them?

**Comment by ccuser44** [comment]
I just don't want them to be saved. Besides they are kinda useless and use up the datastore.

**Comment by ccuser44** [comment]
They are useless as `:shutdownlogs` exists. Also making the max log size larger was useless.

There should be an option to disable them. In my opinion it should be on default as most people don't need `:oldlogs` and it is an annoyance.

**Comment by Sceleratis** [comment]
They shouldn't add any negative/impact to the game/server and not using them would be as simple as not using them, and the datastore space used as well should not be much, so I'm still not seeing exactly what the benefit of a toggle would be <.<

**Comment by moo1210** [comment]
Don't see why you would ever want to disable the most key auditing feature for your moderators. You will likely regret disabling it when you want it. Say a moderator was abusing commands in the command bar in your game while you're asleep making your players leave. When you wake up the next morning, you see multiple complaints about the abuse. Nobody knows who was doing it and the server that contained the logs already shut down because all the players are left. Even if they ran :shutdown instead of the server naturally closing, you would still only know who ran :shutdown, not who was abusing. You would have to guess if the person who ran :shutdown was doing it in good or bad faith. Also about making the max log size larger is useless, highly disagree for the same reasons above, in fact I believe the max should be as large as the oldlogs DataStore key can handle in JSON form ([currently 4 million](https://developer.roblox.com/en-us/articles/Datastore-Errors#limits)). Also it using DataStore budget shouldn't be an issue, considering how [large they are](https://developer.roblox.com/en-us/articles/Datastore-Errors#limits).

**Comment by ccuser44** [comment]
Even if some players want old logs what negative imoact would a setting to disable it add? Nothing. So why not add it

**Comment by ccuser44** [comment]
> in fact I believe the max should be as large as the oldlogs DataStore key can handle in JSON form (currently 4 million).

Why so? If the point of oldlogs is to prevent abuse why would you eant to see 4 million logs anyways? Why would you want yo known if someone abused 2 years ago. Thag is just plain useless. It only makes sense to see abuse of a few days ago.

**Comment by happyman090** [comment]
Couldn't you just not use the oldlogs feature?

**Comment by moo1210** [comment]
> Why so? If the point of oldlogs is to prevent abuse why would you eant to see 4 million logs anyways? Why would you want yo known if someone abused 2 years ago. Thag is just plain useless. It only makes sense to see abuse of a few days ago.

4 million characters in the encoded JSON form isn't equal to 4 million logs. Has essentially no impact to you and has no cost, so you may as well use it. Having audit logs for a few days isn't good practice in the event you need it a few weeks later. I'm not going to debate over bad practices anymore, go look it up for yourself instead.
Though you should probably show how the pros of disabling oldlogs outweigh the cons, or just don't run :oldlogs.

**Comment by GalacticInspired** [comment]
useless 

maybe to abuse in games with it disabled to not get caught?

**Comment by ccuser44** [comment]
> maybe to abuse in games with it disabled to not get caught?

Not really as only devs can change it anyways.

**Comment by joritochip** [comment]
I think it's safe to close this... it has been a while and nobody other than the author has expressed an interest in this. Plus, the desired functionality can be accomplished with a plugin.
