### ISSUE TITLE
ERROR:CanKeepAlive is not a valid member of Folder "HelpButton.Config"

### ISSUE THREAD

**Issue by maska228** [Sceleratis/Adonis#339]
![image](https://user-images.githubusercontent.com/67519438/118118380-0b31e980-b417-11eb-822f-584af2c8aad4.png)

**Comment by Sceleratis** [comment]
What theme are you using?

**Comment by maska228** [comment]
> What theme are you using?

 i think its BasicAdmin

**Comment by TheLegendarySpark** [comment]
> > What theme are you using?
> 
> i think its BasicAdmin

It's actually the HelpButton, not the theme folder `Basic Admin`. If you take a glance at the error, it directly shows what asset it is.

**Comment by Sceleratis** [comment]
> > > What theme are you using?
> > 
> > 
> > i think its BasicAdmin
> 
> It's actually the HelpButton, not the theme folder `Basic Admin`. If you take a glance at the error, it directly shows what asset it is.

All UI elements are part of a theme, so I was wondering if this is the default HelpButton or if this was a different one that was in a theme they were using. After reviewing the code I think I get why it's happening (cuz HelpButton is generated on demand rather than being premade with a config folder n stuff and I guess I just forgot to include CanKeepAlive as a thing in the generated folder...)

**Comment by Sceleratis** [comment]
nvm not actually sure why this is happening rn but I assume you aren't using the default theme (?)

**Comment by maska228** [comment]
> nvm not actually sure why this is happening rn but I assume you aren't using the default theme (?)

I set the theme to BasicAdmin through client options

Cant provide more info rn as i dont have acces to my pc
