### ISSUE TITLE
Size doesn't work with R15

### ISSUE THREAD

**Issue by ProperSyntax** [Sceleratis/Adonis#61]
![image](https://user-images.githubusercontent.com/40641958/42289069-890e0cbc-7f8b-11e8-8af4-26d6a9f1bbeb.png)

**Comment by Sceleratis** [comment]
it should be using humanoidrootpart (?)

**Comment by ProperSyntax** [comment]
It checks for "Torso" as well. 
![image](https://user-images.githubusercontent.com/40641958/45601120-cfc88e00-b9d5-11e8-8b61-5541d064eb7b.png)

**Comment by Sceleratis** [comment]
ugh qq

**Comment by Brandon-Beck** [comment]
Humanoid based character scaling was introduced with R15: ([documentation](https://developer.roblox.com/api-reference/class/Humanoid), [Release Announcement with example code](https://devforum.roblox.com/t/r15-character-scaling/30642), [Example Resize Accessories](https://devforum.roblox.com/t/r15-character-scaling/30642/53))
Really useful for scaling.

```lua
local scale = 1
if humanoid:FindFirstChild("BodyHeightScale") then
	humanoid.BodyHeightScale.Value = scale 
end
if humanoid:FindFirstChild("BodyWidthScale") then
	humanoid.BodyWidthScale.Value = scale 
end
if humanoid:FindFirstChild("BodyDepthScale") then
	humanoid.BodyDepthScale.Value = scale 
end
if humanoid:FindFirstChild("HeadScale") then
	humanoid.HeadScale.Value = scale 
end
```

Have not yet played with the rthro/custom charas yet, nor done any odd disproportionate scaling. Since I saw this, ill post it since it seems slightly related and may affect someone: https://devforum.roblox.com/t/rthro-scaling-specification/199611
