### ISSUE TITLE
Trello admin not working

### ISSUE THREAD

**Issue by kwzeith** [Sceleratis/Adonis#802]
admin with trello isnt working for me

**Comment by Expertcoderz** [comment]
Please describe your issue in greater detail so that we can help you.
- Has Trello worked for you before? / Is this occurring randomly or all the time?
- Are the admins showing up in ``:adminlist``?
- How is your Trello integration configured (what did you put in the loader settings)?
- How is your Trello board set up/structured (eg. what do you name your lists as)?
- (Any other relevant info if applicable.)

**Comment by Expertcoderz** [comment]
Note: Am closing this issue as unresolved if no further elaboration is provided within 14 days starting from the date this issue was posted.

**Comment by Expertcoderz** [comment]
Closing issue; marking as completed because I'd assume this was tied to an issue that has since been [resolved](https://github.com/Sceleratis/Adonis/commit/4cdef865000225114d0ba1ee29e330d0609a1fc2) in an update.
