### ISSUE TITLE
Adonis will not load in my place

### ISSUE THREAD

**Issue by Jerryghb** [Sceleratis/Adonis#84]
Adonis will not load in the place even after I tried putting a new one and relaunching the game multiple times. No errors.

**Comment by Sceleratis** [comment]
Are you positive the place is saving? Sometimes Roblox won't actually update the place. So far that's been the issue with most reports like this. If you're able to confirm the place is actually updated, and Adonis is in either Workspace or ServerScriptService when you save it, try using a test server & client in studio to see if it runs. Note: Use Test > Start Server (with 1 player) and NOT Play/Solo mode.

**Comment by hexadecimal-berry** [comment]
@Sceleratis This is an issue for a lot of games on the ROBLOX platform. Either if it's the old version or the moved development version. It takes about 10 minutes for it to load and kick only a few people with "ACLI Error". This has been rare and never happened for a while.

**Comment by Sceleratis** [comment]
Right, but there's also the case where it's not loading at all. I'm trying to determine if this specific situation is an actual bug or if the script just isn't running in the first place.

**Comment by NNickey** [comment]
I've only had issues with Adonis failing to load properly when the server was overwhelmed by scripts that are maliciously designed to put a burden on server performance. Scripts like the fire spread, RotateP spread, or scripts that are just poorly scripted with unnecessary loops can cause Adonis to load late, some clients ending up with a kick because Adonis wasn't able to communicate with the client due to flooding of Remote Events.
Be sure you throttle the use of Remote Events as one script can pull the server to an halt.
